### ISSUE TITLE
Yes I think the cache package should go back into the `api` package

### ISSUE THREAD

**Issue by VandeurenGlenn** [VandeurenGlenn/blue_server#6]
> > Yes I think the cache package should go back into the `api` package
> 
> Done!
> 
> edit: o wait, api? I've putted it back in server

Nah I think it makes sense in `api` because that's where you are caching things from no?

_Originally posted by @vdegenne in https://github.com/VandeurenGlenn/blue_server/issues/5#issuecomment-1585612545_

**Comment by vdegenne** [comment]
@VandeurenGlenn want me to do the change?

**Comment by VandeurenGlenn** [comment]
@vdegenne Think it's done already
