### ISSUE TITLE
Trading platforms

### ISSUE THREAD

**Issue by vdegenne** [VandeurenGlenn/blue_server#73]
Would be great to have the trading platforms on `BlueAsset`, at least Binance, Kraken and Coinbase for now.

**Comment by VandeurenGlenn** [comment]
> Would be great to have the trading platforms on `BlueAsset`, at least Binance, Kraken and Coinbase for now.

Did that already ;)

**Comment by VandeurenGlenn** [comment]
Oh, but there is an issue
platforms: asset.contract_address needs to be platforms

**Comment by VandeurenGlenn** [comment]
Nvm, it's correct, platforms contains the contract addresses for the different platforms.
